# **Exercícios**


In [1]:
# importando bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

## **Exercício 1 – Regressão (Previsão do Consumo de Energia)**


In [2]:
# Carregando dataset de regressão
df_energy = pd.read_csv('energydata_complete.csv')
df_energy.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [14]:
# Selecionando features e target
X = df_energy.drop(columns=['date', 'Appliances'])
y = df_energy['Appliances']

# Divisão treino/teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
X_train.shape, X_test.shape

((15788, 27), (3947, 27))

In [15]:
# Modelos de regressão
for nome, modelo in {
    'Regressão Linear': LinearRegression(),
    'Árvore de Regressão': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42)
}.items():
    # Treinamento
    modelo.fit(X_train, y_train)
    y_pred = modelo.predict(X_test)

    # Métricas
    try:
        rmse = mean_squared_error(y_test, y_pred, squared=False)
    except TypeError:
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))

    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)

    # Saída formatada
    print(f'{nome} - R²: {r2:.3f}, RMSE: {rmse:.3f}, MAE: {mae:.3f}\n')


Regressão Linear - R²: 0.169, RMSE: 91.175, MAE: 52.548

Árvore de Regressão - R²: 0.180, RMSE: 90.597, MAE: 38.873

Random Forest - R²: 0.532, RMSE: 68.418, MAE: 32.900



## **Exercício 2 – Classificação (Estabilidade da Rede Elétrica)**

In [7]:
# Carregando dataset de classificação
df_grid = pd.read_csv('smart_grid_stability_augmented.csv')
df_grid.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [17]:
# Separando features e target
X = df_grid.drop(columns=['stabf'])
y = df_grid['stabf'].map({'stable': 1, 'unstable': 0})

# Divisão treino/teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
X_train.shape, X_test.shape

((48000, 13), (12000, 13))

In [18]:
# Modelos de classificação
for nome, modelo in {
    'Regressão Logística': LogisticRegression(max_iter=1000, random_state=42),
    'Árvore de Decisão': DecisionTreeClassifier(random_state=42),
    'KNN': KNeighborsClassifier(),
    # 'Random Forest': RandomForestClassifier(random_state=42)
}.items():
    # Treinamento
    modelo.fit(X_train, y_train)
    y_pred = modelo.predict(X_test)

    # Métricas
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    # Saída formatada
    print(f'{nome} - Acurácia: {acc:.3f}, F1-Score: {f1:.3f}')
    print(f'Matriz de Confusão:\n{cm}\n')

Regressão Logística - Acurácia: 0.965, F1-Score: 0.952
Matriz de Confusão:
[[7480  198]
 [ 219 4103]]

Árvore de Decisão - Acurácia: 1.000, F1-Score: 1.000
Matriz de Confusão:
[[7678    0]
 [   0 4322]]

KNN - Acurácia: 0.825, F1-Score: 0.747
Matriz de Confusão:
[[6820  858]
 [1237 3085]]

